services:
  victoriametrics:
    image: victoriametrics/victoria-metrics:v1.138.0
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "3"
    volumes:
      - ./data/victoriametrics:/victoria-metrics-data
    command:
      - -retentionPeriod=1y
      - -httpListenAddr=:8428

  prometheus:
    image: prom/prometheus:v3.7.3
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "3"
    volumes:
      - ./prometheus/:/etc/prometheus/
      - ./data/prometheus:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana:12.2.1
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "3"
    user: nobody
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./data/grafana:/var/lib/grafana

  replicator:
    build: .
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
    volumes:
      - ./data/replicator:/data
    command:
      - --couchdb-url=<COUCHDB_URL>
      - --couchdb-username=<COUCHDB_USERNAME>
      - --couchdb-password=<COUCHDB_PASSWORD>
      - --couchdb-database=registry
      - --log-level=info
      - --webhooks-enabled

networks:
  web_default:
    external: true
