apiVersion: 1

datasources:
  - name: VictoriaMetrics
    type: prometheus
    access: proxy
    orgId: 1
    uid: "default_prometheus_ds"
    url: http://victoriametrics:8428
    basicAuth: false
    isDefault: true
    jsonData:
      timeInterval: 15s
      tlsAuth: false
      tlsAuthWithCACert: false
